# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=64)),
                ('Apellido', models.CharField(max_length=64)),
                ('Documento', models.IntegerField(max_length=64)),
                ('Telefono', models.IntegerField(max_length=64)),
                ('EMail', models.EmailField(max_length=120)),
                ('FNacimiento', models.DateField()),
            ],
        ),
    ]
