# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='Documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='Telefono',
            field=models.IntegerField(),
        ),
    ]
