# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionales',
            name='Apellido',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profesionales',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profesionales',
            name='Nombre',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
