# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionales', '0002_auto_20170314_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='Apellido',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='profesionales',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profesionales',
            name='Nombre',
            field=models.CharField(max_length=64),
        ),
    ]
