# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionales', '0003_auto_20170317_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesionales',
            old_name='Email',
            new_name='EMail',
        ),
    ]
