# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profesionales', '0001_initial'),
        ('Contactos', '0004_auto_20170122_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contactos.Contactos')),
                ('Profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profesionales.Profesionales')),
            ],
            options={
                'verbose_name': 'Historia Clinica',
                'verbose_name_plural': 'Historias Clinicas',
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinicaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaConsulta', models.DateField(auto_now_add=True)),
                ('Descripcion', models.TextField()),
                ('Tratamiento', models.TextField()),
                ('HistoriaClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.HistoriaClinica')),
            ],
            options={
                'verbose_name': 'Linea de Historia Clinica',
                'verbose_name_plural': 'Lineas de Historia Clinica',
            },
        ),
    ]
