# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriaClinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='Alergias',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='Antecedentes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='Diagnostico',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='Nombre',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinicadetalle',
            name='Descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinicadetalle',
            name='Tratamiento',
            field=models.TextField(null=True),
        ),
    ]
